### ISSUE TITLE
Don't add block to ipfs

### ISSUE THREAD

**Issue by rava-dosa** [rava-dosa/NAV-Chain#2]
In IPFS you can't delete a file. So add only if the block is accepted by the network
[Remove here](https://github.com/rava-dosa/NAV-Chain/blob/baf596bee7889837b5d961f61ca3fbb7037f00b2/Miner/Miner.py#L48)

**Comment by Gjhakgp** [comment]
This issue is solved, the block which has recieved the consensus is created in createblockforpublishing  in Miner.py file to be pushed in ipfs
